# Generated by Django 2.0.1 on 2018-05-04 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def update(apps, schema_editor):
    User = apps.get_model('users', 'User')
    TelegramPreferences = apps.get_model('users', 'TelegramPreferences')
    for u in User.objects.all():
        a = TelegramPreferences(user=u)
        a.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enableTelegram', models.BooleanField(default=False)),
                ('chatId', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(update)
    ]
