# Generated by Django 2.0.1 on 2018-05-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrampreferences',
            name='enableTelegram',
        ),
        migrations.AddField(
            model_name='telegrampreferences',
            name='notifyProfile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrampreferences',
            name='notifyProject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrampreferences',
            name='notifyTask',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrampreferences',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrampreferences',
            name='verifyToken',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
