# Generated by Django 2.0.1 on 2018-05-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180504_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrampreferences',
            name='chatId',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
