# Generated by Django 2.0.1 on 2018-01-30 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='membered_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('statusChangeDate', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('doin', 'Doing'), ('done', 'Done')], default='todo', max_length=4)),
                ('actif', models.BooleanField(default=True)),
                ('prerequisites', models.ManyToManyField(to='projects.Task')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('tags', models.ManyToManyField(to='projects.Tag')),
                ('userAssigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
