# Generated by Django 2.0.1 on 2018-04-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dependants',
            field=models.ManyToManyField(blank=True, related_name='dependanted_by', to='projects.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='prerequisited_by', to='projects.Task'),
        ),
    ]
