# Generated by Django 2.0.1 on 2018-01-30 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180130_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='actif',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='actif',
            new_name='active',
        ),
    ]
