# Generated by Django 2.0.1 on 2018-02-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180131_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('primary', 'Bleu'), ('secondary', 'Gris'), ('success', 'Vert'), ('danger', 'Rouge'), ('warning', 'Jaune'), ('info', 'Bleu ciel'), ('light', 'Clair'), ('DARK', 'Sombre')], max_length=20),
        ),
    ]
