# Generated by Django 2.0.1 on 2018-05-02 11:17

from django.conf import settings
from django.db import migrations, models


def update(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for u in Project.objects.all():
        u.admins.add(u.owner)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0002_auto_20180410_1429"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="admins",
            field=models.ManyToManyField(
                related_name="administrated_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RunPython(update),
        migrations.RemoveField(model_name="project", name="owner",),
    ]
