# Generated by Django 3.1a1 on 2020-06-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='chatId',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
