# Generated by Django 3.1a1 on 2020-06-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200605_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
